[workspace]

members = [
    "aggregator",
    "baby-liminal-extension",
    "bin/node",
    "bin/runtime",
    "finality-aleph",
    "pallets/aleph",
    "pallets/baby-liminal",
    "pallets/elections",
    "pallets/support",
    "primitives",
]

exclude = [
    "aleph-client",
    "benches/payout-stakers",
    "bin/cliain",
    "contracts/adder",
    "contracts/poseidon_host_bench",
    "e2e-tests",
    "flooder",
    "fork-off",
    "poseidon",
    "relations",
    "relations/src/proc_macro",
    "scripts/synthetic-network/synthetic-link",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
