[package]
name = "finality-aleph"
version = "0.1.0"
authors = ["Cardinal Cryptography"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.21", features = [ "sync" ]}
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
log = "0.4"
futures = "0.3"
parity-util-mem = "0.9"
parking_lot = "0.11"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
rand = "0.8"
rush = { git = "https://github.com/Cardinal-Cryptography/rush.git", branch = "main" }
sp-keystore = {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sc-network = {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sc-network-gossip = {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sc-telemetry = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}

serde = "1.0"
sc-service = {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-application-crypto = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-core = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-runtime = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-utils = { version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-api = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-blockchain = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-consensus= {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sc-client-api = {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-io= {version = "3", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
derive_more = "0.99.7"
# we need aura authorites till we have our own pallet
sp-consensus-aura = {version = "0.9", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
env_logger = "0.8.3"
async-trait = "0.1.42"