version: '3'
services:

  smartnode:
    image: $NODE_IMAGE
    container_name: smartnode
    network_mode: host
    environment:
      - CUSTOM_ARGS=--log runtime::contracts=debug
      - ALLOW_PRIVATE_IPV4=true
      - BASE_PATH=/data/$NODE_ID
      - CHAIN=/data/chainspec.smartnet.json
      - DISCOVER_LOCAL=true
      - NAME=Smartnode
      - NODE_KEY_PATH=/data/$NODE_ID/p2p_secret
      - RPC_PORT=9933
      - WS_PORT=9944
      - PORT=30333
      - VALIDATOR_PORT=30343
      - PURGE_BEFORE_START=true
      - RUST_LOG=info
      - UNIT_CREATION_DELAY=300
      - BOOT_NODES=/ip4/127.0.0.1/tcp/30333/p2p/$BOOTNODE_PEER_ID
      - PUBLIC_ADDR=/ip4/127.0.0.1/tcp/30333
      - PUBLIC_VALIDATOR_ADDRESS=127.0.0.1:30343
    volumes:
      - ./data/:/data/
