[package]
name = "aleph-node"
version = "0.9.0"
authors = ["Cardinal Cryptography"]
description = "Aleph node binary"
edition = "2021"
build = "build.rs"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "aleph-node"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
libp2p = "0.49.0"
thiserror = "1.0"

sp-application-crypto = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-block-builder = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-chain-spec = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning"}
sc-cli = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-core = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-executor = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-service = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-telemetry = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-keystore = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-keystore = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-inherents = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-basic-authorship = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-network = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-transaction-pool = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-transaction-pool = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-transaction-pool-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-consensus-aura = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-consensus-aura = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-consensus = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-consensus = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-client-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-runtime = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-timestamp = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
pallet-staking = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
try-runtime-cli = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning", optional = true }
sc-consensus-slots = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-arithmetic = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }

aleph-runtime = { path = "../runtime" }
finality-aleph = { path = "../../finality-aleph" }
aleph-primitives = { package = "primitives", path = "../../primitives" }

# These dependencies are used for the node's RPCs
jsonrpsee = { version = "0.15.1", features = ["server"] }
sc-rpc = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sc-rpc-api = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-blockchain = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
sp-block-builder = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
substrate-frame-rpc-system = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }
pallet-transaction-payment-rpc = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "cardinal-test-pruning" }

[features]
default = []
short_session = [
    "aleph-runtime/short_session",
    "aleph-primitives/short_session"
]
try-runtime = [
    "aleph-runtime/try-runtime",
    "try-runtime-cli",
]
enable_treasury_proposals = [
    "aleph-runtime/enable_treasury_proposals"
]
only_legacy = [
    "finality-aleph/only_legacy"
]
