[package]
name = "aleph-runtime"
version = "0.1.0"
authors = ["Cardinal Cryptography"]
edition = "2018"
license = "Apache 2.0"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

primitives = { path = "../../primitives", version = "0.1.0", default-features = false }
pallet-aleph = { package = "pallet", path = "../../pallet", version = "0.1.0", default-features = false}



frame-election-provider-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
frame-executive = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
frame-system = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}

pallet-aura = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-balances = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-session = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-staking = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-staking-reward-curve = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-sudo = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
pallet-transaction-payment = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}

sp-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-block-builder = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-consensus-aura = { version = "0.9.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-inherents = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-npos-elections = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-offchain = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-session = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-staking = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-transaction-pool = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}
sp-version = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}

pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "681f188"}


[build-dependencies]
substrate-wasm-builder = { version = "4.0.0"}

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-aleph/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
    "sp-offchain/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "frame-system-rpc-runtime-api/std",
	"primitives/std",
]
