---
#  This workflow builds docker from aleph-node test binary and docker from e2e client binary
name: Build test node image and e2e client image
on:
  workflow_call:

jobs:
  build-test-node-image:
    name: Build test node docker image and e2e client image
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Download test artifact
        uses: actions/download-artifact@v3
        with:
          name: aleph-test-node
          path: target/release/

      - name: Build test docker image
        id: build-image
        run: |
          chmod +x target/release/aleph-node
          docker build --tag aleph-node:latest -f ./docker/Dockerfile .
          docker save -o aleph-node.tar aleph-node:latest

      - name: Upload test docker image
        uses: actions/upload-artifact@v3
        with:
          name: aleph-test-docker
          path: aleph-node.tar
          if-no-files-found: error
          retention-days: 7

  build-and-push-aleph-e2e-client-image:
    name: Build and push aleph-e2e-client-image
    uses: ./.github/workflows/_build-and-push-e2e-client-image.yml
    with:
      push: true
