---
#  This workflow builds test version of aleph-node and aleph-runtime, ie with some
#  features enabled. Those binaries MUST NOT be used in the production.
name: Build test node and runtime
on:
  workflow_call:
    inputs:
      ref:
        description: "git ref: hash, branch, tag or 'mainnet' or 'testnet'"
        type: string
        required: true
      build-e2e-tests-targets:
        description: 'Set to true if aleph-node image and aleph-e2e-client should be built'
        type: boolean
        required: false
        default: false

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  build-artifacts:
    name: Build test node and runtime
    needs: [check-vars-and-secrets]
    runs-on: [self-hosted, Linux, X64, large]
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout aleph-node source code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/getA0-2800-fix-get-ref-properties-ref-properties@A0-2800-fix-get-ref-properties

      - name: Install Rust toolchain
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v4
        with:
          targets: wasm32-unknown-unknown

      - name: Build test binary and runtime
        run: |
          cargo build --release -p aleph-node \
            --features "short_session enable_treasury_proposals only_legacy"

      - name: Ensure liminal symbols are not present
        run: |
          nm --demangle=rust target/production/aleph-node | grep -q liminal \
            && { echo "Liminal symbols are present"; exit 1; } \
            || echo "Liminal symbols are not present"

      # this is required for some workflows, yet ideally it should not be required
      - name: Upload test binary to GH Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aleph-test-node
          path: target/release/aleph-node
          if-no-files-found: error
          retention-days: 7

      - name: Build test docker image
        if: ${{ inputs.build-e2e-tests-targets == true }}
        id: build-image
        run: |
          chmod +x target/release/aleph-node
          docker build --tag aleph-node:latest -f ./docker/Dockerfile .
          docker save -o aleph-node.tar aleph-node:latest

      # this is solely required by action/run-e2e-test.yml, also it should not be required
      - name: Upload test docker image
        if: ${{ inputs.build-e2e-tests-targets == true }}
        uses: actions/upload-artifact@v3
        with:
          name: aleph-test-docker
          path: aleph-node.tar
          if-no-files-found: error
          retention-days: 7

      - name: Build aleph-e2e-client image
        if: ${{ inputs.build-e2e-tests-targets == true }}
        run: |
          cd e2e-tests/
          rm -f target/release/deps/aleph_e2e_client*
          cp $(cargo test --no-run --release --message-format=json | jq -r .executable | \
            grep aleph_e2e_client) target/release/aleph-e2e-client

      - name: Login to Public Amazon ECR
        if: ${{ inputs.build-e2e-tests-targets == true }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ECR_PUBLIC_HOST }}
          username: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: Push aleph-e2e-client to ECR
        if: ${{ inputs.build-e2e-tests-targets == true }}
        env:
          IMAGE: aleph-e2e-client
          TAG: ${{ steps.get-ref-properties.outputs.sha }}
          REGISTRY: ${{ vars.ECR_PUBLIC_REGISTRY }}
        run: |
          cd e2e-tests/
          registry='${{ env.REGISTRY }}'
          image_and_tag='${{ env.IMAGE }}:${{ env.TAG }}'
          docker build --tag ${registry}${image_and_tag} -f Dockerfile .
          docker push ${registry}${image_and_tag}
          if [[ '${{ steps.get-ref-properties.outputs.branch }}' -eq 'main' ]]; then
            docker tag ${registry}${image_and_tag} ${registry}'${{ env.IMAGE }}:latest'
            docker push ${registry}'${{ env.IMAGE }}:latest'
          fi
