---
name: Build and push aleph-node liminal image.

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build binary
    runs-on: self-hosted
    steps:
      - name: GIT | Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Cargo | Build release binary
        run: cargo build -p aleph-node --release --features liminal

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: AWS | Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: DOCKER | Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: DOCKER | Build and push docker image
        id: build-image
        uses: docker/build-push-action@v3
        env:
          REGISTRY: public.ecr.aws/p6e8q1z1/
          IMAGE_NAME: aleph-node-liminal
          TAG: ${{ steps.get-ref-properties.outputs.sha }}
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ env.TAG }}
