---
name: Test featurenets create and update scenarios (normal session)

on:
  schedule:
    # At 03:40 on Wednesday
    - cron: '40 3 * * 3'
  workflow_dispatch:
  # tmp, remove
  push:
    branches:
      - A0-3735

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  get-fqdn-via-tag:
    name: Get aleph-node main branch FQDN image (short session)
    needs:
      - check-vars-and-secrets
      - delete-branch-featurenet
    runs-on: ubuntu-20.04
    outputs:
      fqdn-image: ${{ steps.get-aleph-node-fqdn-image.outputs.fqdn-image }}
      ref: ${{ steps.get-aleph-node-fqdn-image.outputs.ref }}
      image-exists: ${{ steps.get-aleph-node-fqdn-image.outputs.image-exists }}
    steps:
      - name: Get aleph-node fqdn path
        id: get-aleph-node-fqdn-image
        uses: Cardinal-Cryptography/github-actions/get-aleph-node-fqdn-image@v6
        with:
          ref: 'r-12.2'
          test-binary: 'true'
          # temp, revert
          # ecr-dev-node-repo: ${{ vars.ECR_DEV_ALEPH_NODE_REPO }}
          ecr-dev-node-repo: 'public.ecr.aws/p6e8q1z1/aleph-node-dev'
          ecr-prod-node-repo: ${{ vars.ECR_ALEPH_NODE_REPO }}

  build-and-push-featurenet-node-image-via-tag:
    needs: [get-fqdn-via-tag]
    if: ${{ needs.get-fqdn-via-tag.outputs.image-exists != 'true' }}
    name: Build and push PR test docker image
    uses: ./.github/workflows/_build-and-push-featurenet-node-image.yml
    with:
      ref: ${{ needs.get-fqdn-via-tag.outputs.ref }}
      fqdn-image: ${{ needs.get-fqdn-via-tag.outputs.fqdn-image }}
      short-session: true
    secrets: inherit

  create-featurenet-via-tag:
    needs:
      - get-fqdn-via-tag
      - build-and-push-featurenet-node-image-via-tag
    # to prevent this job to be skipped when on of the parent jobs is skipped
    if: ${{ !cancelled() }}
    name: Create featurenet from tag
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v6
    secrets: inherit
    with:
      featurenet-name: 'ops-test-main-tag'
      aleph-node-image: ${{ needs.get-fqdn-via-tag.outputs.fqdn-image }}
      validators: '6'
      expiration: '2h'
      internal: true
      delete-first: true

  delete-tag-featurenet:
    needs: [create-featurenet-via-tag]
    if: ${{ always() }}
    name: Delete featurenet
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-delete.yml@v6
    secrets: inherit
    with:
      featurenet-name: 'ops-test-main-tag'

#  slack:
#    name: Slack notification
#    runs-on: ubuntu-20.04
#    needs: [delete-tag-featurenet]
#    if: >
#      !cancelled() &&
#      github.event_name != 'workflow_dispatch'
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Send Slack message
#        uses: ./.github/actions/slack-notification
#        with:
#          notify-on: "failure"
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV_ONDUTY }}
