---
name: Runs button e2e test on push to main branch

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    name: Deploy button
    uses: ./.github/workflows/_deploy_button.yml
    with:
      deploy: true
    secrets: inherit
